### ISSUE TITLE
Using GroupOperation

### ISSUE THREAD

**Issue by jshier** [danthorpe/Operations#42] opened 2015-08-11 00:04 UTC
I'm having trouble understanding how to use `GroupOperation`. I have a networking layer (Alamofire based) that I've wrapped in a `NetworkOperation` (`Operation` subclass). I want to create `GroupOperation` subclasses that allow me to encapsulate these `NetworkOperation`s along with some optional operations that should be done if the initial network request fails with a particular error (user token expired). I must be doing something wrong though, as I keep hitting the "Cannot add new operations to a group after the group has completed." assertion, likely because I'm losing the race between the `GroupOperation` automatically finishing and my operations starting the next one in the sequence in the completion block. Perhaps you can give me a better idea. Here's the code for my `StatusOperation` I'm building as a prototype for the other `GroupOperation`s.
```swift
class StatusOperation : InterruptibleNetworkOperation {
    let completionHandler: (Status?, Error?) -> Void
    let fetchFromAllServers: Bool
    
    init(account: Account, fetchFromAllServers: Bool, completionHandler: (Status?, Error?) -> Void) {
        self.fetchFromAllServers = fetchFromAllServers
        self.completionHandler = completionHandler
        super.init(operations: [])
        
        if #available(iOS 8.0, *) {
            name = "Account Status"
        }
        
        let statusOperation = statusOperationWithAccount(account, fetchFromAllServers: fetchFromAllServers, completionHandler: completionHandler)
        
        addOperation(statusOperation)
    }
    
    func statusOperationWithAccount(account: Account, fetchFromAllServers: Bool, completionHandler: (Status?, Error?) -> Void) -> NetworkOperation {
        return NetworkOperation(request: Manager.manager.request(Router.Status(account: account, fetchFromAllServers: fetchFromAllServers))) { (status: Status?, error: Error?) -> Void in
            if let error = error where error.isExpiredUserTokenError {
                self.handleExpiredUserTokenError()
            }
            else {
                self.completionHandler(status, error)
                self.emptyOperation.finish()
            }
        }
    }
    
    override func successOperationWithAccount(account: Account) -> Operation {
        return statusOperationWithAccount(account, fetchFromAllServers: fetchFromAllServers, completionHandler: completionHandler)
    }
}
```
And here's `InterruptibleNetworkOperation`:
```swift
class InterruptibleNetworkOperation : GroupOperation {
    let emptyOperation = EmptyOperation()
    
    override init(operations: [NSOperation]) {
        super.init(operations: operations + [emptyOperation])
    }
    
    func handleInvalidTokenError() {
        addOperation(AccountRefreshOperation(completionHandler: { (account) in
            guard let account = account else {
                return
            }
            
            log("*** Issuing second call. ***")
            self.addOperation(self.successOperationWithAccount(account))
        }))
    }
    
    func successOperationWithAccount(account: Account) -> Operation {
		// Should always be overridden.
        return BlockOperation(mainQueueBlock: {
            self.emptyOperation.finish()
        })
    }
}
```
The assertion fails when I try to run `self.addOperation(self.successOperationWithAccount(account))` in `InterruptibleNetworkOperation`, presumably because the `AccountRefreshOperation` (sends an `NSNotification` to a view controller to login, receives notifications about whether the user logged in and returns the account object or nil) has completed but the next operation hasn't been added yet, as the completion handler is still executing. As you can see, I tried to work around the issue by having an `EmptyOperation` (just overrides `execute()` with an empty body) which I could `finish()` manually but it doesn't seem to have done the trick. 

So the question is, how can I structure this logic using the Operations library? I am using the Swift 2 branch but I'm perfectly happy to pull in code from the development branch. 

Also, any general suggestions for passing data between operations without having to resort to custom completion handlers all the time?

**Comment by danthorpe** [comment] 2015-08-11 09:36
Hi @jshier - thanks for getting in touch - I hope I can help resolve the problem (I know that documentation is sorely lacking).

My initial thoughts are:

1. Can you share the `NetworkOperation` class - just how it sets up, executes, and calls finish?
2. In `InterruptibleNetworkOperation` I think you can drop the `emptyOperation`, as `GroupOperation` already has exactly this concept, and it's private queue's delegate uses it to manage when to end the group. 
3. And I think this is the root cause, your child operations are calling this group's empty operation's `finish` call, instead of their own.
4. To handle the errors in your `Interruptible...` class, over-ride the `operationDidFinish` method, and use this to inspect the errors of the operation, and then call `addOperation` from there.
5. Can you change your `NetworkOpertion` so that instead of returning the error in a completion block, it instead calls `self.finish(error: error)`?

Let me know if those points change anyway, I'll see if I can re-write your code sample, and I'll share some examples of how I'm using in `GroupOperation`.

**Comment by danthorpe** [comment] 2015-08-11 10:18
Also, if you're using the `swift_2.0` branch - this is quite a way behind `development` and is likely going to cause you some problems. I'm updating it now in #43.

**Comment by danthorpe** [comment] 2015-08-11 13:45
Okay, the swift_2.0 branch is now at version 0.10.1 (the latest). You should now be able to put this into your `InterruptibleNetworkOperation`:

```swift
override func operationDidFinish(operation: NSOperation, withErrors errors: [ErrorType]) {
    // check what the operation is, and if the error is recoverable from
    // call addOperation with new instance.
}
```

I would probably consider refactoring your `NetworkOperation` so that you have a protocol `NetworkOperationType`, and then write you `InterruptibleNetworkOperation` like this:

```swift
class InterruptibleNetworkOperation<O: Operation where O: NetworkOperationType>: GroupOperation {
    var operation: O
    init(operation: O) {
           self.operation = operation
           self.init(operations: [operation])
    }

    override func operationDidFinish(operation: NSOperation, withErrors errors: [ErrorType]) {
        if self.operation == operation let error = errors.first as? NetworkOperation.Error {
            switch error {
                case .InvalidToken:
                // At this point you need to create your AccountRefreshOperation
                // add it as a dependency to a copy of the original operation, and then 
                // add them both.
            }
        }
    } 
}
```

**Comment by danthorpe** [comment] 2015-08-11 13:55
But... I'll just add here, that all of this is not really the best way of doing what you want to do. I don't know much about your network stack, but I would turn your invalid token logic into an operation condition. Something like...

```swift
struct ValidNetworkCredentialsCondition: OperationCondition {
  // look in Operations for example of how to implement this.
}
```

The condition needs to be able to evaluate itself - you could do something like use a TTL for your credentials?

Also the condition can provide a dependency operation which will be executed before it is evaluated. Here you can incorporate your `AccountRefreshOperation`. So, essentially you would check a TTL `NSDate` and return `AccountRefreshOperation` as a dependency of the condition. You can then incorporate this logic into `NetworkOperation` directly, and you don't need to have `InterruptibleNetworkOperation`.

Something like...

```swift
class NetworkOperation: Operation {
    init(request: Request) {
      // etc etc
      super.init()
      name = "Network Operation: \(request)"
      addCondition(ValidNetworkCredentialsCondition())
    }

    override func execute() {
        // guaranteed to have valid credentials at this point.
    }
}
```

**Comment by jshier** [comment] 2015-08-11 15:57
Unfortunately the user tokens can't just expire but also be invalidated by the same account logging in somewhere else, so any network call to my backend (which I have little influence over) can fail with expired token error. 

Here's the `NetworkOperation` source you asked for. I'm using Argo in combination with Alamofire for the underlying `Request`s . So I'm already using `finish(error)`.
```swift
class NetworkOperation : Operation {
    let request: Request
    
    init<T: Decodable where T == T.DecodedType>(request: Request, completionHandler: (T?, APIError?) -> Void) {
        self.request = request
        
        super.init()
        
        request.responseObject { (responseObject: T?, error: APIError?) in
            completionHandler(responseObject, error)
            self.finish(error)
        }
        
        addObserver(NetworkObserver())
        //addObserver(BackgroundObserver())
    }
    
    override func execute() {
        request.resume()
    }
    
    override func cancel() {
        request.cancel()
        super.cancel()
    }
}
```
I'll give your suggested architecture a go but I'm still wondering how I can use the delegate method you suggested and my completion blocks, which return strong types, at the same time. I'll let you know how it goes.

Also, any chance of official iOS 7 support? It's fairly easy with Swift 2, even if all I did was mark all of the unavailable APIs with `@available(iOS 8.0, *)`, which may or may not be a good way to do it. Really the only things I can see actually being back ported, since most aren't available on 7 at all (CloudKit, etc.) would be the `AlertOperation` and `ReachabilityCondition`. I could even contribute the changes if you're interested.

**Comment by danthorpe** [comment] 2015-08-11 16:11
Okay, so I guess it's not possible to create an condition.

I didn't mention a delegate method however, there are no delegates. So, what you should do, is remove the error parameter from your `NetworkOperation`'s completion block. Instead, handle errors via the failure mechanism of `Operation`. Like this:

```swift
class NetworkOperation<Response where Response: Decodable, Response.DecodedType == Response>: Operation {
   enum Error: ErrorType {
      case RequestFailed(underlyingError: APIError?)
   }

   let request: Request

init<T: Decodable where T == T.DecodedType>(request: Request, completionHandler: T? -> Void) {
        self.request = request

        super.init()

        request.responseObject { (responseObject: T?, error: APIError?) in
            guard let error = error {
                 self.finish(error)
                 return
            }
            completionHandler(responseObject)
            self.finish(error)
        }

        addObserver(NetworkObserver())
    }

    override func execute() {
        request.resume()
    }

// etc

}
```

I think you initial assessment of what is going on is correct, because inside your completion block you were calling finish on that empty operation, which was happening before the network operation itself finished.

If you do the above, you'll be able to inspect the error inside your `InterruptibleNetworkOperation` as I showed a few comments above.

**Comment by danthorpe** [comment] 2015-08-11 16:13
Regarding iOS7 - I hadn't really thought about it, but I guess in the Swift 2.0 branch then I can make it work all the way to iOS 7, so yeah will be happy to do it.

**Comment by danthorpe** [comment] 2015-08-11 16:14
FYI - made a few mistakes in that code example - updated it a few times, if you're only going by GitHub's emails.

**Comment by jshier** [comment] 2015-08-11 22:11
The logic you posted:
```swift
override func operationDidFinish(operation: NSOperation, withErrors errors: [ErrorType]) {
    if self.operation == operation let error = errors.first as? NetworkOperation.Error {
        switch error {
            case .InvalidToken:
            // At this point you need to create your AccountRefreshOperation
            // add it as a dependency to a copy of the original operation, and then 
            // add them both.
        }
    }
}
```
I'm not sure this is going to work. My `AccountRefreshOperation` leads to two options. Either the user has successfully logged in again and the `Account` has been refreshed, or the user has logged out, in which case it's pretty easy to return a special error and check for it in `operationDidFinish(_: withErrors:)`. However, to regenerate the original operation with the new account information, I can't generate the operation until the refresh operation has completed, one way or another. Which means I can't add the regenerated operation as a dependency of the refresh operation. I suppose I could abuse the errors returned and return a LoggedIn case. I'll see how that works.

**Comment by jshier** [comment] 2015-08-11 23:20
@danthorpe Thanks for the help. Here's what I've come up with so far. I didn't do the protocol you suggested, as I couldn't get it to work cleanly with the subclasses and the operations need to be regenerated at the group level, not the operation level, since `NetworkOperation` is generic as to the request and completion handler fed into it.
```swift
class NetworkOperation : Operation {
    let request: Request
    
    init<T: Decodable where T == T.DecodedType>(request: Request, completionHandler: (T?, APIError?) -> Void) {
        self.request = request
        
        super.init()
        
        request.responseObject { (responseObject: T?, error: APIError?) in
            if let error = error where error.isInvalidTokenError {
                self.finish(error)
            }
            else {
                completionHandler(responseObject, error)
                self.finish(error)
            }
        }
        
        addObserver(NetworkObserver())
    }
    
    override func execute() {
        request.resume()
    }
    
    override func cancel() {
        request.cancel()
        super.cancel()
    }
}

class InterruptibleNetworkOperation : GroupOperation {
    var primaryOperation: Operation
    
    init(operation: Operation) {
        primaryOperation = operation
        
        super.init(operations: [operation])
    }
    
    override func operationDidFinish(operation: NSOperation, withErrors errors: [ErrorType]) {
        guard let error = errors.first else {
            return
        }
        
        if let error = error as? APIError where error.isInvalidTokenError {
            let refreshOperation = AccountRefreshOperation()

            addOperation(refreshOperation)
        }
        else if let error = error as? RefreshCompletionState, case .LoggedOut = error {
            // Do nothing?
        }
        else if let error = error as? RefreshCompletionState, case .LoggedIn = error {
            let repeatOperation = regenerateOperationForNewAccount()
            
            addOperation(repeatOperation)
        }
    }
    
    func regenerateOperationForNewAccount() -> Operation {
        return EmptyOperation()
    }
}

class AccountStatusOperation : InterruptibleNetworkOperation {
    let finalCompletionHandler: (AccountStatus?, APIError?) -> Void
    let passedFetchFromAllServers: Bool
    
    init(fetchFromAllServers: Bool, completionHandler: (AccountStatus?, APIError?) -> Void) {
        self.passedFetchFromAllServers = fetchFromAllServers
        self.finalCompletionHandler = completionHandler
        
        let operation = AccountStatusOperation.AccountStatusOperation(fetchFromAllServers, completionHandler: completionHandler)
        
        super.init(operation: operation)
        
        if #available(iOS 8.0, *) {
            name = "Account Status"
        }
    }
    
    static func AccountStatusOperation(fetchFromAllServers: Bool, completionHandler: (AccountStatus?, APIError?) -> Void) -> NetworkOperation {
        let request = APIManager.manager.request(APIRouter.AccountStatus(account: AccountManager.selectedAccount!, fetchFromAllServers: fetchFromAllServers))
        return NetworkOperation(request: request, completionHandler: completionHandler)
    }
    
    override func regenerateOperationForNewAccount() -> Operation {
        return AccountStatusOperation.AccountStatusOperation(passedFetchFromAllServers, completionHandler: finalCompletionHandler)
    }
}
```
Any issues you can see? I'm going to try implementing my other calls with this pattern and see if I run into any more issues.

**Comment by danthorpe** [comment] 2015-08-12 09:05
Err, well I don't really like there is an error that isn't an error? But I also didn't quite follow where the `RefreshCompletionState` comes from? It looks as though like your network layer mixes authentication/authorization state with errors so there isn't much else you can do but mix your control logic with your errors too.

Writing this framework it's been quite instructive to see how Apple's APIs deal with authorisation, and authorisation state. For Location, Photos, Contacts, AddressBook, CloudKit, HealthKit, PassKit, Notifications - they all have subtle differences, but all of them have bespoke enums to indicate the "authorization" status, e.g. allowed, denied, restricted. In the case of a network layer, I think you want the same thing, an enum to indicate the authorization, with associated values representing credentials (accounts, tokens etc). You've said that you don't have any control over the network backend - this is often the case, but in my experience, it can help to isolate the client from architectural decisions made by the backend. So, maybe you should think about writing your own bit of middleware that sits in the client and mediates between your Operations and the Request type.

**Comment by jshier** [comment] 2015-08-12 18:23
I added the `RefreshCompletionState` enum as an `ErrorType` because that seemed to be the easiest way to get the state of the refresh from the `AccountRefreshOperation` to `InterruptibleNetworkOperation`. Perhaps some expansion of the API to allow for data besides errors would be a good idea?

There is no authorization state in this app. Like I said, we get a token back with the login call which can be invalidated at any moment and the only way to tell is to try a call and see if it fails with the appropriate error. So I'm not sure what any sort of middleware would look like in this case. Or really, I intended the operations to be be this middleware and automatically renew tokens as failures come in. There is no part of the app that can be used without the user being logged in and no other authorizations states than logged in, which doesn't change until the user logs out (either from a specific location in the app or from the login dialog that pops up when the token is invalidated).

So I'm not sure what the middleware you're thinking of would look like or what value it would add. I'll see how implementing the rest of my network calls this way goes.

**Comment by danthorpe** [comment] 2015-08-12 18:28
> Perhaps some expansion of the API to allow for data besides errors would be a good idea?

Operations (and NSOperations) are classes - they can store their own state. There is no need to pass everything via completion handlers. If a GroupOperation subclass maintains references to its child operations, and you need to pass data or state from one child to another, then storing the data in properties, is a good way to achieve this. e.g. Operation A stores it's results, when it finishes, the parent group can access these properties and set them on another operation, which it can then add.

> So I'm not sure what the middleware you're thinking of would look like or what value it would add. 

Fair enough - I don't know how your network layer is designed.

**Comment by danthorpe** [comment] 2015-08-12 18:30
@jshier I'm going to close this issue, not really sure how much more I can help you. I will use some of the things we've discussed here in some sample code, wiki pages as part of the documentation for GroupOperations.

**Closed by danthorpe** 2015-08-12 18:30 UTC
Labels: example, help wanted, question
