### ISSUE TITLE
GroupOperation with AlertOperation not finishing

### ISSUE THREAD

**Issue by bastianschilbe** [danthorpe/Operations#174] opened 2016-02-03 15:35 UTC
If I add an AlertOperation to a GroupOperation the finish observer of the AlertOperation gets called but the outer GroupOperation never finishes. It seems that the containing UIOperation contained in the AlertOperation is scheduled on the GroupOperation queue but is never finished so the group cannot finish. Do I miss something here?
```
let group = GroupOperation()
group.addOperation(AlertOperation(presentAlertFrom: self))
group.addObserver(FinishedObserver(didFinish: { _, _ in print("expected") }))
queue.addOperation(group)
```

**Comment by danthorpe** [comment] 2016-02-03 15:40
Hi @bastianschilbe - this in interesting, could be a bug. 

I'm assuming that you're dismissing the `UIAlertController` that is presented? If so, I think your expectations are justified.

I'll take a look into it tonight, hopefully get back to you.

**Comment by danthorpe** [comment] 2016-02-11 18:23
Hi @bastianschilbe, can you check this again now on the latest `development`? Thanks!

**Comment by malhal** [comment] 2016-02-12 23:11
The Alert Operation was designed by Dave Delong who is not a UIKit developer and instead of solving his problems using UI methods he has opted to make a super complicated wrapper via his NSOperation framework. This library should come with a warning that it shouldn't be used by programmers already proficient in UIKit and all beginners. In his talk on this at WWDC I remember him saying there are issues with alerts that they can appear on top of each other (false) and in fact with the new alert controller it is impossible to even present two alerts because the second gets dropped. Given his background in operations he has attempted to solve this using that but in fact the solution is to fix the alert controller to allow sequential alerts, how the original UIAlertView worked, if you know UIKit you know how to solve this problem.

If you run the eaethqaukes sample you'll experience all kinds of UI bugs, including if you tap an earthquake then tap more info, dismiss the safari controller then try to tap more info again you will find it won't work and the Operation queue is blocked. This is because he didn't know that the safari controller dismisses itself when the done button is pressed, thus the dismiss with completion has no effect and the completion does not fire thus the operation never ends. its crazy to me there is all this bloat and convoluted code and he claims it's so powerful yet it falls over in the simplest of cases. This I think the library should come with a severe health warning.

**Comment by malhal** [comment] 2016-02-12 23:13
And by the way same thing with CloudKit, it already has an internal queue that runs sequentially so there is no reason to wrap it up in more operations.

And same thing with NSURLSession.

**Comment by jshier** [comment] 2016-02-12 23:28
@malhal I don't think you understand the point of this library, or operations in general. This library, and the Advanced NSOperations talk and code that preceded it, provides the foundation for and wrapper around common asynchronous tasks used by developers on Apple's platforms. It does this to expose the added functionality of operations, namely dependency chaining, cancellation, conditions, and observers, to system, that, while already asynchronous, can benefit from one of those abilities. For example, `NSURLSession` offers no ability to chain requests together, perform them simultaneously, or pass results between tasks, despite these needs being rather common in apps with more than simple networking needs. If you were to write code to accomplish these goals using only the capabilities provided by `NSURLSession`, you would end up with a rats nest of of nested completion handlers and global state. Using operations, on the other hand, you're able to create chains of requests that can easily pass state between them while operating in a guaranteed order. Plus all of the other features operations bring.

Now, if you find that there are bugs with some of the operations offered, feel free to files issues, as with an open source project. If you feel that some operations are flawed in their implementation, file issues as well. But jumping into an existing issue with off base comments that don't offer anything relevant to the current discussion is both impolite and disrespectful. 

If you'd like to raise issues or open PRs feel free to do so, but unprompted and hyperbolic whining is unwelcome, both here and on GitHub in general (IMO).

**Comment by malhal** [comment] 2016-02-13 00:21
Hi Jon sorry I didn't meant to sound like I was whining. The reason I posted here is the OP's alert did not finish the operation because it is not using UIKit correctly. So the people watching this thread, which is referenced by other operation github projects btw, would all understand the inherent design flaw in this library. And no offense you to or any of the collaborators it's not your fault, it is the fault of this particular Apple engineer that created it. If you try his earthquakes example you'll witness just now crazy and convoluted it is, and the outcome is an app that doesn't even work.

Also what you said about NSURLSession is incorrect. It is itself an operation queue and does support everything you mention. It's a common mistake in iOS programming to attempt to reimplement what one lesser known framework does using advanced knowledge of another framework, which is exactly what is going on here.

**Comment by danthorpe** [comment] 2016-02-13 10:43
@bastianschilbe - sorry your bug report has been hijacked here. I am still looking into your issue. 😃

Thanks to @jshier for the timely & excellent response 👍. I'm really grateful to have supporters and advocates in this project!

@malhal please [create a new issue](https://github.com/danthorpe/Operations/issues/new) if you have experienced a bug or have constructive feedback, for the code *in this project*. If you have information related to a specific class or operation in this project, or have information so that I can "use UIKit correctly", also please share it in a new issue, and I will listen to suggestions and criticisms gladly. 

The contributors to this project have spent relatively significant effort, for *free*, over the course of 6 months to build something which they feel is useful to themselves and maybe others. If you do not, you are more than welcome to not use it.

If you just want to blast Apple developers, or anyone else, for their contributions to a community, please don't - just [be nice](https://realm.io/news/altconf-orta-therox-being-nice-in-open-source/). If you want to have a philosophical discussion about the tradeoffs of adopting this or any open source framework, I suggest Twitter, Facebook or other social media is a better outlet. I encourage everyone to perform due-diligence before integrating any 3rd party framework.

**Comment by danthorpe** [comment] 2016-02-14 14:33
@bastianschilbe this bug should now be fixed on `development` branch.

**Comment by danthorpe** [comment] 2016-02-17 10:37
I'm closing this ticket now - v2.6 is released.

**Closed by danthorpe** 2016-02-17 10:37 UTC
Labels: bug, fixed, waiting for response
