### ISSUE TITLE
NSError vs ErrorType?

### ISSUE THREAD

**Issue by sixten** [danthorpe/Operations#78] opened 2015-09-11 17:40 UTC
One of the major differences between the original Apple sample code and this project seems to be that you've replaced the usage of `NSError` in the original with your `ErrorType` marker protocol. Can you explain a little about your motivations for doing so, and how you'd expect client code to use these values?

Leaving aside the frustrating issues with Swift 1.2 / Xcode 6 printing enums, it seems like quite a few of the cases defined in the error enums in these conditions end up wrapping `NSError` values from some other API. And it seems like trying to do something useful with the error list of an operation (possibly a composition of many conditions and sub-operations) would require a lot of speculative casting or filtering for enums you know about. But it's quite possible that there's something about this setup that I'm just not getting.

Looking forward, with Swift 2 bringing more integration for `NSError`-based error handling, does that change your mind at all?

**Comment by danthorpe** [comment] 2015-09-13 13:21
Hi, this is a great question. Firstly, I wrote most of foundation/building blocks of the project using Swift 2, and then back-ported it to Swift 1.2. So, I started with an `ErrorType` protocol and I feel that this is going to be more forward compatible with Swift 2.

Yes, some of the system frameworks which have operations may produce `NSError` or `CFError` errors which are then provided as a underlying error.

My reasoning for this setup is that consumers of the framework will still need to diagnose the errors that they receive, whether they be `NSError` or just enums implementing `ErrorType`. Using the enum can give the framework an error "layer" above the wrapped frameworks, which allows us to 

1. Wrap the returned errors with added type safety & fidelity. E.g. take a look at the [`AddressBook.Error`](https://github.com/danthorpe/Operations/blob/development/Operations/AddressBook/AddressBook.swift#L677) which gives you the gist of the error as part of its type.
2. Differentiate between errors from with the Operations framework and those from without, with much greater ease than error domains and error codes.

For an example of how this would be done only using `NSError` you can see how CloudKit handles errors, which typically will have nested `NSError`s inside a parent error's userInfo dictionary. I think this is actually a lot harder to learn catch and process. So, despite Swift 2's integration of `NSError` based APIs, I don't have any current plans to change this. However, I will almost certainly revisit the wrapped frameworks to see if there are improvements to be made to increase discoverability.  

The only unfortunate thing at the moment is that `enum` don't get description for free in Swift 1.2, and they can't be extended by subclasses. And the first issue - the biggest one for discoverability, is fixed in Swift 2. 

As for how I expect consumers to use this... 

1. Use `GroupOperation` and override `operationDidFinish(: NSOperation, withErrors: [ErrorType])` where a typical implementation might look like...

```swift
override func operationDidFinish(operation: NSOperation, withErrors errors: [ErrorType]) {
    if errors.isEmpty {
        // perhaps inspect the finishing operation, retrieve results, create/add a new operation
    }
    else {
       if let error = errors.first as? MyOperation.Error {
            switch error {
                case .MissingInfo:
                    // resolve the error, add a new operation?,
            }
       }
    }
}
```

For example. Of course, depending on what operations you are using, then you may also want to optionally case the first error to that operations `Error` type if it has one.

Also, only bother handling the 1st error - as this is likely the cause of any other errors, and typically you will want keep trying an operation until it finishes with no errors, fixing the first error at each repetition.

2. Use a `BlockObserver` - this is pretty much how all of the unit tests work to check that the correct errors are thrown, and is the best way to add error handling to situations where you only have one operation to run once, so no need for a group, and it's not a custom operation where you could include the error handling inside the operation. Use it like this...

```swift
operation.addObserver(BlockObserver { (_, errors) in
  // same strategy of optionally cast & unwrap the first error
})
```

**Comment by danthorpe** [comment] 2015-09-13 13:25
One thing which I've been toying with and likely to happen in the near future is more built in logging mechanism into `Operation` directly - so this will help during development to make sure that your operations are executed as expected.

But, also perhaps a more specific `ErrorObserver` which would allow consumers to reuse error handling code. This would be great for errors like, login & authentication, no network etc. Where the error can pop up anywhere, and you need a consistent handler. You can do this now by just creating bespoke `BlockObserver`s but I feel that the framework itself should provide something like this, and could potentially include some standard error handlers.

**Closed** 2015-09-16 10:41 UTC
Labels: question
