### ISSUE TITLE
swift_conformsToProtocol deadlock in state change setter

### ISSUE THREAD

**Issue by itsthejb** [danthorpe/Operations#254] opened 2016-03-25 13:19 UTC
Hi Dan,

Another one of these related to `swift_conformsToProtocol`, as before. It would seem that these parts of the Swift runtime aren't thread safe... In any case, same issue as http://stackoverflow.com/questions/33788606/apparent-deadlock-in-alamofire-request-method, in fact. The deadlock is caused by two threads entering https://github.com/apple/swift/blob/2ded9fe4447553050f08a4d1afe3c92d57b93390/stdlib/public/runtime/ProtocolConformance.cpp#L568.

In this case, it's caused by the logging https://github.com/eyeem/Operations/blob/36fbe8baf495fbc1d752b53d724e261c89e57fec/Sources/Core/Shared/Operation.swift#L288. It's fine for us to just comment that out. Also, I can try the older version you suggested.

**Comment by danthorpe** [comment] 2016-03-25 13:28
Oh, interesting... Is that with `.Verbose` log severity set?

**Comment by itsthejb** [comment] 2016-03-25 13:29
Yes

**Comment by itsthejb** [comment] 2016-03-25 13:29
And also - we are basically still on 2.7.1. Can't update to Swift 2.2 quite yet

**Comment by danthorpe** [comment] 2016-03-25 13:29
And, with `> .Verbose` severity it doesn't deadlock?

**Comment by danthorpe** [comment] 2016-03-25 13:31
Okay... does this deadlock happen on Xcode 7.2? Or Xcode 7.3?

**Comment by itsthejb** [comment] 2016-03-25 13:31
7.2. Are you suggesting this something that's fixed in Swift 2.2? If so, we could certainly do our builds with 7.3, even though our test suite is stuck on <2.2 for now...

**Comment by itsthejb** [comment] 2016-03-25 13:33
You mean < Verbose? Possibly, hard to check since it's kinda intermittent.

**Comment by danthorpe** [comment] 2016-03-25 13:34
No, not suggesting that at all. Just trying to keep my head straight with all the changes!  😬

But, essentially, what we're saying here is that this deadlock issue has nothing to do with Xcode 7.3 or Swift 2.2. And it's either always been here, or is a regressions introduced by 2.8.0, 2.8.1 or 2.8.2?

**Comment by danthorpe** [comment] 2016-03-25 13:35
Err - I guess I mean closer to `.Fatal` then `.Verbose` 😉

**Comment by itsthejb** [comment] 2016-03-25 13:37
No, we're on Operations 2.7.1. Probably can't update to the newer version since we're still on Swift 2.1 for now. I'm guessing it doesn't happen with the logging turned down, because we wouldn't enter that section.

**Comment by danthorpe** [comment] 2016-03-25 13:37
The reason I'm asking about the log severity is that the logger has a dedicated queue - and the message is in an auto closure. If the severity level is not met, then nothing happens. But, potentially there is an issue with whatever is in the message is causing a deadlock between queues?

**Comment by danthorpe** [comment] 2016-03-25 13:39
Yep - so regarding versions. All released versions so far right up to `2.8.2` are for Swift 2.1. Here are the changes from 2.7.1 -> https://github.com/danthorpe/Operations/compare/2.7.1...2.8.2

**Comment by itsthejb** [comment] 2016-03-25 13:42
Ah ok - we should probably pull forward. Let me look into that. So many version numbers! Swift, Xcode, Operations...!

**Comment by danthorpe** [comment] 2016-03-25 13:45
Yeah - sorry, it's been a bit of a crazy week. I had 3 bug fixes from contributors right in the middle of the switch.

So, probably the best thing to do is to follow my `swift/2.1` branch until you're ready to switch to Swift 2.2. This branch has all of these changes, and will effectively be the "development" branch for Swift 2.1 / Xcode 7.2. So if you make any pull requests - send them there instead of to `development`. 👍

**Comment by itsthejb** [comment] 2016-03-25 13:45
Ok, great, will check that out now

**Comment by danthorpe** [comment] 2016-03-25 13:46
In the mean time - I'm going to release `2.9.0` now, which is for *Swift 2.2*...

**Comment by itsthejb** [comment] 2016-03-25 13:49
:+1:

**Comment by danthorpe** [comment] 2016-03-25 13:57
Also - another thing which you might want to look into, is using a custom logger for Operations. See the example project [here](https://github.com/danthorpe/Examples/blob/development/Operations/Permissions/Permissions/AppDelegate.swift#L22) which uses SwiftyBeaver for logging.

**Comment by itsthejb** [comment] 2016-03-25 14:01
Yes - in fact we're wiring through CocoaLumberjack now (for the file logging possibilities, mostly). Previously Loggerithm, but that didn't have the support for multiple log outputs

**Comment by danthorpe** [comment] 2016-04-01 11:03
Hi @itsthejb how did the app release go?

Just checking in to see if there is any update on this?

**Comment by danthorpe** [comment] 2016-04-06 06:09
Hi @itsthejb - gonna close this for now. Feel free to re-open it if you are still experiencing this issue.

**Closed by danthorpe** 2016-04-06 06:09 UTC
Labels: waiting for response
