### ISSUE TITLE
Completion block isn't called in ~0.1% of cases when a condition is attached.

### ISSUE THREAD

**Issue by bastianschilbe** [danthorpe/Operations#175] opened 2016-02-03 19:50 UTC
If you have a operation and prevent it from running by a failed condition, the completion callback isn't always called. Try the following with an iOS test target:
```
    func test__multiple_operations_completion_blocks() {
        
        let q = OperationQueue()
        (0...5000).forEach { i in
            let e = expectationWithDescription("wait\(i)")
            let operation = BlockOperation(block: { _ in XCTFail() })
            operation.addCompletionBlock({ e.fulfill() })
            let condition = BlockCondition(block: { false })
            operation.addCondition(condition)
            q.addOperation(operation)
        }
        waitForExpectationsWithTimeout(8, handler: nil)
    
    }
```
I see about 1-10 expections unfulfilled.
Do I use conditions the wrong way?

**Comment by danthorpe** [comment] 2016-02-03 19:58
Hmm, interesting - I'll have a look into this, too.

There isn't anything special in the framework regarding `completionBlock` - it's just the same behavior as `NSOperation`. The documentation is a little vague about when the completion block is executed. Have you written this test because you've noticed some odd or random behavior?

I tend to use `FinishedObserver` instead of completion blocks, as it's more clearly defined when it is executed. E.g.

```swift
func test__multiple_operations_completion_blocks() {

    let q = OperationQueue()
    (0...5000).forEach { i in
        let e = expectationWithDescription("wait\(i)")
        let operation = BlockOperation { XCTFail() }
        operation.addObserver(FinishedObserver { _, _ in e.fulfill() })
        let condition = BlockCondition { false }
        operation.addCondition(condition)
        q.addOperation(operation)
    }
    waitForExpectationsWithTimeout(8, handler: nil)
}
```

But, regardless, your test should work. Might just be an issue with your `BlockOperation`.

**Comment by bastianschilbe** [comment] 2016-02-03 20:12
Yes I've tested it with the FinishObserver with the same result.
I've some nested GroupOperations and some operations in them have a condition which is failing and the finishedObserver isn't called. I've already spent some time to track down the issue but I'm kind of lost. It seems to be some sort of race condition. If I slow down the .forEach loop by a logging breakpoint with each iteration the chances that more expectations are fulfilled are raising. Hope you can help with that. If I can help you somehow let me know

**Comment by danthorpe** [comment] 2016-02-03 20:25
Hmm, okay. Can you describe or share a simplified example of the nested `GroupOperation` where this occurs? Just sharing the `init` and `execute` implementations of the GroupOperation` would help me to see how your nesting is supposed to work.

Have you turned on `.Verbose` logging? If you turn it on for the outer group operation it should cascade to the child operations. This will log out all the state transitions for each operation, which is really useful for sanity checking the scheduling.

e.g.

```swift
let operation = MyOperation()
operation.log.severity = .Verbose
```

**Comment by bastianschilbe** [comment] 2016-02-03 20:51
I'm trying to provide a simplified test case. Just need some time.
If that helps: the unfulfilled operations seem to be in state .Ready and still on the operation queue. The conditions on them were evaluated.

**Comment by danthorpe** [comment] 2016-02-03 20:54
Okay, could well be a lock issue inside the state. Hopefully, the verbose state changes can reveal if a dependency has not finished.

I'm working on another issue right now, but I'll come back to this and use your loop test case as a starting point.

**Comment by pronebird** [comment] 2016-04-10 15:39
I made a sample project that somewhat resembles a very simple version of Operations.

https://github.com/pronebird/NSOperationReproducingRaceCondition

There is no problem as long as operation transitions to `.Ready` once super.isReady turns true. However, everything breaks if operation transitions to `.Ready` anytime later (think evaluator).

That seems to be the case with Operations too, because Operations switches to `.Ready` from within `isReady` if there are no any conditions set. I just ran a long test without any conditions and everything works fine.

**Comment by danthorpe** [comment] 2016-04-10 15:48
@pronebird - yeah, we confirmed that adding conditions certainly makes the issues 100% reproducible given enough `Operation` instances. I debugged the evaluator quite carefully - could well be the bug I suppose.

One possible avenue to investigate is to re-create using `NSOperation` only, and add an operation dependency to each invoked operation. If this makes the bug reproducible, then it adds more weight to there being a bug in `NSOperation`, `NSObject` and KVO. If not - then will probably mean the condition evaluator is the culprit.

**Comment by pronebird** [comment] 2016-04-10 22:19
@danthorpe updated my repository. Added simple async operation that does not control readiness, chained 500 operations with dependencies. Everything is fine. Something tells me we simply cannot safely manipulate isReady.

**Comment by danthorpe** [comment] 2016-04-11 08:09
@pronebird okay, so, it looks like adding some asynchronous logic around `ready` causes issues - either due to conditions (asynchronous evaluator) or mutual exclusivity (asynchronous exclusion lock). Will try to find the time to debug it more this week.

**Comment by pronebird** [comment] 2016-04-12 13:05
Another extra bit of information: 

calling `-cancel` on .Ready operation does in fact pumps up the queue, operation then receives `-start` properly. `-cancel` method of NSOperationInternal manually fires KVO notification for `isReady`.

**Comment by pronebird** [comment] 2016-04-13 16:28
I've been trying to fix this for entire week. 

The only solution I came up with was to chop off Operation state and get back to good old override of `isExecuting` and `isFinished`. I don't override `isReady` as it seems to create all kind of havoc in NSOperation internals.

Condition evaluator is simply wrapped in block operation and added as dependency for main operation to run. Evaluation errors are then passed back to main operation before it executes. This way operation readiness is defined purely by dependencies.

**Comment by danthorpe** [comment] 2016-04-13 16:48
This is fantastic - okay, I will take this approach and do a refactor of `Operation`. Really really appreciate all your efforts on this.

If you want to put your changes together into a PR that would be great - but no worries if you don't want to. I want to refactor conditions into `Operation` instances anyway.

**Comment by pronebird** [comment] 2016-04-13 19:47
@danthorpe 

Thanks for brainstorming and debugging with me!

I'd love to help with PR, however I am afraid I am really behind the schedule with my app since I killed about a week trying to approach the problem in a less radical way. You can take a look at my PR for Operative and adapt it for Operations.

I wrote stress tests for Operative. Currently we run about 1M operations in batches on both mutually exclusive and async tests. Not a single memory leak or crash.

I'll make more tests to make sure that everything runs in order. But after manual testing it, something tells me that it's gonna be alright.

🍻🍻🍻

**Comment by phausler** [comment] 2016-04-13 20:51
see https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSOperation.swift at line 59 for some background on why this is the case. Unfortunately the completion block is a bit cagey and dependencies should be used if order is important.

**Comment by jshier** [comment] 2016-04-13 20:53
@phausler The open source Foundation implementation of `NSOperation` has nothing to do with the implementation offered by Foundation on Apple platforms.

**Comment by danthorpe** [comment] 2016-04-26 05:50
This is now fixed in `development` 😀

A massive thanks to @pronebird who did the bulk of the work in actually figuring out the issue was due to  `isReady` getting overridden.

The change, which refactors operation conditions as `Condition` an `Operation` and executed as a dependency may require some refactoring. `Operation` will accept the old style `OperationCondition` but you will find that dependencies for the condition are added / queried when the condition is attached, which is different than from before.

**Closed by danthorpe** 2016-04-26 05:50 UTC
Labels: bug, in progress

**Comment by pronebird** [comment] 2016-04-27 17:23
@danthorpe good good. Did you happen to tackle a problem of dependencies between long running ops and conditions that use mutual exclusivity, for example:

1. LocationOperation (Location Exclusivity) -> LocationPermissionOperation (Alert exclusivity)
2. LocationOperation (Location Exclusivity) -> LocationPermissionOperation (Alert exclusivity)
3. AlertOperation (Alert exclusivity)

So if first op runs for a long time, let's say 15 seconds (real use case scenario). It happens that second location permission operation won't start until 1st location operation has finished. At the same time, if you display alert, well everything gets in a long waiting queue. 

Did you happen to tackle this particular case in Operations and how did you solve it? :)

**Comment by danthorpe** [comment] 2016-04-27 17:40
@pronebird I haven't really looked at this kind of scenario.

There are still some things which I want to write tests for. So, this big change is going to be a v3.0 thing, and not going to get released for a couple of weeks. I can certainly look at this sort of issue though.

One thing which has come up separately, is that `Operation` would support a timeout observer by default - and especially in `UserLocationOperation` for example. There is an issue for this: #217.
