### ISSUE TITLE
Alamofire & Operations

### ISSUE THREAD

**Issue by GUL-** [danthorpe/Operations#173] opened 2016-01-25 21:36 UTC
How can we use Alamofire and Operations framework all together?

**Comment by jshier** [comment] 2016-01-25 22:02
It's pretty easy to wrap Alamofire using operations, but unless your needs are simple, you'll probably be better off writing your own. I have a semi-generic `NetworkOperation` that wraps Alamofire, so I'll post that up when I get a chance.

**Comment by danthorpe** [comment] 2016-01-25 22:20
Thanks @jshier - I'd add pretty much the same.

Regular `NSOperation` instances can be wrapped using `ComposedOperation`, and `URLSessionTask` can be wrapped using `URLSessionTaskOperation`.

You could try these to see how Operations works for you. e.g. setup your network request using Alamofire and then compose the underlying task inside `URLSessionTaskOperation`. I should probably add a guide for this as I guess it's a common use case.

However, writing your own `Operation` subclass or using `URLSessionTaskOperation` as a starting point will allow you to tailor something bespoke to your network layer.

Also note: in `development` branch (should be released as v2.6 in a week or so) `ComposedOperation` has been refactored. It has the same interface but will look differently if you're browsing the code here v.s. looking at the code from CocoaPods.

**Comment by jshier** [comment] 2016-01-26 03:03
Here's the `NetworkOperation` I created that uses Alamofire.
```swift
class NetworkOperation<T: Decodable where T == T.DecodedType> : Operation, NetworkOperationType {
    
    private(set) var result: Result<T, APIError>?

    private let request: URLRequestConvertible
    private let completionQueue: dispatch_queue_t?
    private let completionHandler: ((result: Result<T, APIError>?) -> Void)?
    
    private var activeRequest: Request?
    
    private var currentQueue: NSOperationQueue? { return NSOperationQueue.currentQueue() }
    
    init(request: URLRequestConvertible, completionQueue: dispatch_queue_t? = nil, completionHandler: ((result: Result<T, APIError>?) -> Void)? = nil) {
        self.request = request
        self.completionQueue = completionQueue
        self.completionHandler = completionHandler
        
        super.init()
        
        name = "NetworkOperation<\(T.self)>"
    }
    
    override func execute() {
        guard !cancelled else { return }
        
        activeRequest = Alamofire.request(request).responseObject(queue: currentQueue?.underlyingQueue) { (response: Response<T, APIError>) in
            self.result = response.result
            
            if let completionHandler = self.completionHandler {
                dispatch_async(self.completionQueue ?? dispatch_get_main_queue()) { completionHandler(result: self.result) }
            }
            
            self.finish(response.result.error)
        }
    }
    
    override func cancel() {
        guard !cancelled else { return }
        
        activeRequest?.cancel()
        super.cancel()
    }
}
```
It depends on this Alamofire extension:
```swift
extension Request {
    func responseObject<T: Decodable where T == T.DecodedType>(queue queue: dispatch_queue_t? = nil, completionHandler: (response: Response<T, APIError>) -> Void) -> Self {
        return response(queue: queue, responseSerializer: Request.ArgoResponseSerializer(), completionHandler: completionHandler)
    }
    
    static func ArgoResponseSerializer<T: Decodable where T == T.DecodedType>() -> ResponseSerializer<T, APIError> {
        return ResponseSerializer { (request, response, data, error) in
            let JSONResult = Request.JSONResponseSerializer().serializeResponse(request, response, data, error)
            guard case let .Success(responseJSON) = JSONResult else {
                return .Failure(APIError.Network(error: JSONResult.error!))
            }
            
            let parsedJSON = JSON.parse(responseJSON)
            let decodedObject = T.decode(parsedJSON)
            guard case let .Success(responseObject) = decodedObject else {
                return .Failure(APIError.Decode(error: decodedObject.error!))
            }
            
            return .Success(responseObject)
        }
    }
}
```
Which in turns depends on [Argo](https://github.com/thoughtbot/Argo) for JSON parsing and my own `APIError` type. This is an example of the type of specialization you'll likely need. But you can see how you could wrap the basic Alamofire `response` functions like this.

**Comment by danthorpe** [comment] 2016-01-26 07:07
@jshier @GUL- yeah, this is pretty ace.

Much better than my initial suggestion of wrapping the task inside the Alamofire request.

Also, it shows the general structure for wrapping asynchronous functionality from other systems.

1. Initialize the `Operation` subclass with dependencies.
2. Override `execute` and begin/start/resume the asynchronous task.
3. Use a completion block to set results, call a completion block provided to the operation.
4. Inside the completion block, at the end, call `self.finish(anyError)` to "finish" the Operation.
5. Override `cancel` to stop the async task as quickly as possible. i.e. either as above, or using some internal state which can be checked inside the completion block.

As for having bespoke support in this framework for using Alamofire - I've thought about it, but ultimately, I just think that it's a little bit beyond the scope of this project. It's too much to maintain support for. It's also something which likely each consumer will want to tweak or customize slightly differently, so will be very hard to get something which is common and useful to all. I think it's better to just allow consumers of this framework to write their own networking `Operation` subclasses. This ticket can now work as some great documentation until I add something to the guide.

Thanks @jshier for answering this.

@GUL- does this help you out, and answer your questions?

**Comment by GUL-** [comment] 2016-01-26 08:29
@danthorpe It's the exact help and example I needed. I will test it in my own app as soon as possible.
Many thanks to both of you @jshier and @danthorpe

**Closed** 2016-01-26 14:11 UTC
Labels: documentation, question

**Comment by gk11** [comment] 2016-12-08 18:27
It seems that as of swift 3/ProcedureKit 4, currentQueue?.underlyingQueue returns the dispatch queue only for the main queue.  
Is there any way to get the underlying DispatchQueue of the current non-main Operation/ProcedureQueues - without initially assigning the underlyingQueue  property to a specific queue?

**Comment by danthorpe** [comment] 2016-12-08 20:11
@gk11 - not sure really. 

Accessing the underlying queue of `Foundation.OperationQueue` is best avoided as it is deliberately not deterministic due to the nature of lib dispatch. Indeed, the main queue is the only one guaranteed to exist.

**Comment by jshier** [comment] 2016-12-08 20:13
Which is why that property is nil on `OperationQueue` unless you set the queue yourself. I don't think this has ever worked without setting it, and if ProcedureKit is returning `main` when that's not actually the `underlyingQueue`, that's certainly a bug.

**Comment by danthorpe** [comment] 2016-12-08 20:27
_ProcedureKit_ overrides the `.main` property, (to return the main `OperationQueue` as a `ProcedureQueue` - but it does not override `.current`, so this might be either as expected (e.g. the underlying queue is getting set to the main queue), or it's a change in behaviour as part of Swift 3 / iOS 10 / OS X 10.12.

Probably best to create a new issue to track this any further, as I don't think it's related to networking or Alamofire.

**Comment by gk11** [comment] 2016-12-14 17:08
Thanks for the responses.  The underlyingQueue property is nil when accessed in non main-tread queues. If that works as designed, then there is no issue.
