### ISSUE TITLE
Can't add NetworkObserver to an operation

### ISSUE THREAD

**Issue by gsimmons** [danthorpe/Operations#325] opened 2016-05-27 13:26 UTC
I get a compile error - "Use of unresolved identifier 'NetworkObserver'". Adding DidFinishObserver or TimeoutObserver works fine.

I don't know if it's related, but I also get odd errors in the editor, as if Xcode can't find the framework - "'Operation' is unavailable: cannot find Swift declaration for this class"

I installed via Carthage and did the following:
- Added correct line to Cartfile
- carthage update
- Added framework to project / embedded binaries / linked frameworks
- Added the carthage/build/iOS folder to framework search path
- Added run script build phase for "carthage copy-frameworks" (This is according to Carthage instructions

None of this has made any difference.

Thanks,
Glen

**Comment by danthorpe** [comment] 2016-05-27 20:34
Hi @gsimmons - will look into this. There are some issue with Carthage and the whole Extensions compatible version of the framework.

**Comment by yageek** [comment] 2016-06-18 14:38
I suppose the problem is the fact that Both `.xcodeproj` files produce a framework with the same name. Would it be possible to change the name of the second one ?

**Comment by danthorpe** [comment] 2016-06-18 15:06
Yeah. Spoke to Mike Ferris (program manager for Xcode) about this. The issue is that the framework name must match the module name for the OS (dyld) to locate the framework. 

I have a solution - but is a major breaking change so will happen along side name changes / major version.

**Comment by yageek** [comment] 2016-06-18 15:16
Would it not be more simple for the default project to have a product named `Operations` and for the other one `OperationsExtended` or something similar ?

**Comment by danthorpe** [comment] 2016-06-18 15:57
Yes, this is what is going to happen.

**Comment by danthorpe** [comment] 2016-07-02 14:45
Closing this as its effectively a duplicate of #112.

The solution is going to be the larger scale work of refactoring the structure of the framework, which will be done along with the name and project changes before Swift 3.0 arrives.

**Closed by danthorpe** 2016-07-02 14:45 UTC
Labels: duplicate
