### ISSUE TITLE
malloc: *** error for object ...: incorrect checksum for freed object - object was probably modified after being freed

### ISSUE THREAD

**Issue by ddmus** [danthorpe/Operations#237] opened 2016-03-17 08:52 UTC
Since 2.7.1 I am observing occasional crashes with the above error message. The crash happens in `Operation` class in `state` property setter, either on `willChangeValueForKey("State")` or `didChangeValueForKey("State")`. I observed it on both simulator and iPhone running iOS 9.2. Any ideas about the cause and fix for this? Thank you.

**Comment by danthorpe** [comment] 2016-03-17 09:23
Hi @ddmus - thanks so much for raising this. Do you have any crash logs or stack traces that you can share?

**Comment by danthorpe** [comment] 2016-03-17 09:26
Also, because `Operation` is always subclassed - can you tell what the subclass is? Is it your own subclass - if so, can you share how it is getting finishes?

Initial thoughts suggest that it's getting released/finished by a queue when the state is somehow still changing?

**Comment by ddmus** [comment] 2016-03-17 16:30
![operation-crash](https://cloud.githubusercontent.com/assets/5610919/13852931/cad96298-ec64-11e5-9374-21c8888afc55.png)
Here is the trace when the crash occurs. It's happening on the very begining before the operation starts executing. I just enqueue one of the group operation subclasses.

```
    private func enqueueFullCheck() {
        let fullCheckOperation = FullCheckOperation()
        enqueueMainOperation(fullCheckOperation)
    }
```

And here is the FullCheckOperation that is being added:

```
class FullCheckOperation: GroupOperation {
    
    init() {
        super.init(operations: [])
        addCondition(MutuallyExclusive<FullCheckOperation>())
        MainService.shared.fullCheckEnqueued = true
    }
    
    override func execute() {
        guard !cancelled else { return }
        
        let onBoardingOperation = OnBoardingOperation()
        
        if !LoginService.instance.isUserLogged {
            ...
        }
        
        addOperation(onBoardingOperation)
        
        let loadOperation = LoadOperation()
        loadOperation.addDependency(onBoardingOperation)
        addOperation(loadOperation)
        
        ...adding more operations to the queue and its dependencies...
            
        super.execute()
    }
    
    override func finished(errors: [ErrorType]) {
        NetworkService.shared.lastCheckDate = NSDate()
        MainService.shared.fullCheckEnqueued = false
    }
}
```

Here is the log:
```
[fg211,211,211;[bg;2016-03-17 17:18:52.605 [Verbose] [main] [MainService.swift:121] subscribeToDidBecomeActiveNotification() > active[;
[fg169,169,169;[bg;2016-03-17 17:18:52.607 [Debug] [main] [MainService.swift:163] enqueueFullCheck() > executeFullCheck[;
ApproveIT(7874,0x1a0689000) malloc: *** error for object 0x145e55f48: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
(lldb) 

```
No finishing of this operation, it just waits there for all childs to finish. Any ideas? Thanks.

**Comment by danthorpe** [comment] 2016-03-17 19:35
Thanks for this - will look into considering the diff with 2.7.0 -> 2.7.1

**Comment by danthorpe** [comment] 2016-03-17 20:16
Did you try putting a breakpoint in `malloc_error_break` to debug this?

Also, what does the `enqueueMainOperation()` do? Is that just adding it to a queue?

**Comment by ddmus** [comment] 2016-03-17 21:05
`enqueueMainOperation()` just adds the operation to the mainQueue, nothing else. I am trying to reproduce the crash with the `malloc_error_break` breakpoint. Do I need to specify some module in the breakpoint, or just leave it blank?

Hope I will produce the crash soon, I have not seen it for couple of hours in the afternoon, so I thought I fixed the issue as I did some changes in the code based on your initial feedback. But then later I got this crash again. Btw, I am not sure if it's the issue of the 2.7.1 version of the framework. I may have introduce the issue by myself at the same time when upgrading to the 2.6.0 to 2.7.1. Will keep trying to eliminate the cause.

**Comment by danthorpe** [comment] 2016-03-17 21:07
I don't think it actually matters if you don't specify the module for malloc_error_break - I'm doing a quick google....

**Comment by ddmus** [comment] 2016-03-17 22:13
![operation-crash2](https://cloud.githubusercontent.com/assets/5610919/13862776/99cc4e82-ec95-11e5-9d35-992b576a35d2.png)
I was able to trigger the crash with this trace. Can I somehow dig deeper now to my code where this is triggered? I have not experience with `malloc_error_break`.

**Comment by ddmus** [comment] 2016-03-18 10:06
This is the trace with Address Synthesizer enabled.
![operation-crash4](https://cloud.githubusercontent.com/assets/5610919/13874637/81ad0cf6-ecf9-11e5-8e0a-c2fc5d233537.png)

**Comment by ddmus** [comment] 2016-03-18 10:35
Looking at the trace above with Address Sanitizer enabled, the Thread 3 with ExclusivityManager looked suspicious to me, so I deleted the MutuallyExlusive condition of the FullCheckOperation, as it was anyway not needed, I am using boolean flags to signal the operation is added to the queue, so I don't add it twice (I guess there is better way to do this, but anyway..). When I removed the MutuallyExlusive condition I can no more reproduce the crash. I tried 120 runs on the app without the crash, while before it took around 30 tries to reproduce the crash. So I go with that for now and will report if I see the crash again.

**Comment by danthorpe** [comment] 2016-03-18 11:18
Okay - well that's really helpful for me too!

So, possibly some kind of race-condition / memory issue when adding a mutually exclusive operation to a queue?

Does your operation also have any conditions which have dependencies?

**Comment by danthorpe** [comment] 2016-03-18 11:21
Okay, so thinking more about this - looks like the bug is that we're calling `willEnqueue` when we're also handling the mutual exclusivity stuff, which happens in another thread (I'll need to check how that works again).

So - could be that we're enqueuing (all this does is change the state to `.Pending` I think) when in actually fact we're being held by the exclusivity manager.

Are you absolutely sure that you're only adding one operation? I understand that is the whole point of exclusion, but this bug might be getting raised because you're adding two operations at about the same time?

**Comment by danthorpe** [comment] 2016-03-18 11:23
You can turn on verbose logging too which might help figure out some of the scheduling issues. In your AppDelegate somewhere do this:

```swift
Operations.LogManager.severity = .Verbose
```

**Comment by danthorpe** [comment] 2016-03-20 18:25
Okay, so this is a list of things which changes from `2.6.0` to `2.7.1` in the core "operation" files.

1. Operation.swift
1.1 Writing (i.e. updating) the operation observers is now thread safe.
1.2 Changed the finishing observers, to add "will finish" and "did finish".

2. OperationObserver.swift
2.1 Added `didAttachedToOperation` function to base observer protocol.
2.2 Same change as in Operation for will finish & did finish.

3. OperationQueue.swift
3.1 Special consideration when adding `GroupOperation`. The queue adds an observer to each operation added for `ProducedOperationObserver`. In the case of a `GroupOperation` this adds the produced operation to the group's queue (using `group.addOperation()`) instead of to the receiving queue as normal.
3.2 Added an observer for "will finish" to call the (new) equivalent OperationQueueDelegate method.

**Comment by itsthejb** [comment] 2016-03-25 13:13
Actually we've seen these cropping up, but only in our test suite... I actually have another issue to report with the same section...

**Comment by danthorpe** [comment] 2016-03-25 13:16
Hi @itsthejb, there were some bug fixes related to exclusivity manager in 2.8.1 - so would be good to see if this bug still re-produces?

if you're on Xcode 7.2 & Swift 2.1, then you want to limit your versions to ~> 2.8, or point to branch `swift/2.1`

`development` is now Swift 2.2 and v2.9.0 is about to land....

**Comment by itsthejb** [comment] 2016-03-25 13:17
Ok, cool. Just reporting that issue, but it would *appear* to be Swift related rather than Operations related... Still, hopefully helpful info. With that in a couple of mins.

**Comment by itsthejb** [comment] 2016-03-25 13:22
If it helps at all, we had issues with operation conditions: sooner or later they would hang on evaluating (this is running thousands of the same operations on about 5 threads concurrently). Inspecting the threads didn't reveal a lock, though, they just eventually stopped returning a result and dependent operations wouldn't start

**Comment by danthorpe** [comment] 2016-03-25 13:25
Yeah, that is sort of a known issue which we're still trying to figure out how to solve. 😩🤔 See the discussions here: https://github.com/danthorpe/Operations/issues/175 and https://github.com/danthorpe/Operations/pull/180

The best I can figure is that this is some sort of KVO issue with `NSOperation` - and the problem is sort seems to be made worse when using conditions which have dependencies - possibly because it's just too many operations?

**Comment by ddmus** [comment] 2016-03-25 13:28
For me, 2.8.1 fixed the mutual exclusivity issue which was crashing the app with the malloc error, so I've added back my MutuallyExclusive conditions and have not seen the crash since then.

**Comment by danthorpe** [comment] 2016-03-25 14:40
@ddmus - can we close this issue now then? If it's not reproducible with your original scenario?

**Comment by ddmus** [comment] 2016-03-25 15:02
I agree to close this issue. Thanks.

**Closed** 2016-03-25 15:06 UTC
Labels: bug
