### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by pronebird** [danthorpe/Operations#267] opened 2016-04-08 11:58 UTC
Hi,

I am investigating the issue with stale operations in Operative framework that is built in Objective-C and is very similar to Operations because both frameworks are inspired by Advanced Operations session from WWDC.

Sometimes operations do not start after transition to .Ready state. This creates a congestion in operation queue. Sometimes I see deadlock like this:

<img width="514" alt="screenshot 2016-04-08 12 50 42" src="https://cloud.githubusercontent.com/assets/704044/14382819/942d206a-fd88-11e5-9d0f-c8083bcc4a6e.png">

I already checked Earthquakes app and was able to reproduce similar problem. Relevant gist with ZIP in comments:

https://gist.github.com/pronebird/6ccf4e67030f5fdffe65c941c736181c

This is the operation that I use for testing:

```swift
class TestOperation: Operation {

    override init() {
        super.init()
        
        // you can run it with or without this condition
        // to observe different side effects...
        addCondition(MutuallyExclusive<TestOperation>())
    }

    override func execute() {
        dispatch_async(dispatch_get_main_queue()) {
            print("Finished.")
            self.finish()
        }
    }

}
```

All it does is runs `finish()` on main thread.

This is the method I use to run ops in loops:

```swift

public let sharedQueue = OperationQueue()

func cycle(take: Int) {
        var operations = [Operation]()

        let startOp = BlockOperation {
            print("Begin operations: Take \(take)")
        }

        let endOp = BlockOperation { [weak self] in
            print("End operations")

            print("sharedQueue.operations: \(sharedQueue.operations)")

            if take < 40 {
                self?.cycle(take + 1)
            }
            else {
                print("This is it!")
            }
        }

        for _ in 1...500 {
            let op = TestOperation()

            op.log.severity = .Verbose

            op.addDependency(startOp)

            endOp.addDependency(op)

            operations.append(op)
        }

        operations.append(startOp)
        operations.append(endOp)

        sharedQueue.addOperations(operations, waitUntilFinished: false)
    }
```

Pretty much what happens is based on severity log:

>Unnamed Operation:  <<< MutuallyExclusive<TestOperation>
>Unnamed Operation: Pending -> EvaluatingConditions
>Unnamed Operation: EvaluatingConditions -> Ready

Nothing is going on after that...

You can pull my branch for inspection:

https://github.com/pronebird/Operations/tree/stale-operations

**Comment by danthorpe** [comment] 2016-04-08 12:51
Hi @pronebird - will take a look into this over the weekend

**Comment by danthorpe** [comment] 2016-04-08 18:55
Hi - this looks to be very similar to a bug that has already been investigated: See #175 and #180.

The best we can figure is that it boils down to an issue with KVO.

**Comment by danthorpe** [comment] 2016-04-08 22:14
Yep - pretty sure that this is a duplicate of #175. Gonna close it for now.

**Closed by danthorpe** 2016-04-08 22:14 UTC
Labels: bug
