### ISSUE TITLE
DelayOperation and BlockOperation lack cancellation handlers

### ISSUE THREAD

**Issue by jshier** [danthorpe/Operations#133] opened 2015-12-14 18:02 UTC
I don't know whether this was intentional, but it has lead to some unexpected behavior for me. A simple test like this:
```swift
let delayOperation = DelayOperation(interval: 5)
delayOperation.completionBlock = { print("delay completion block") }
delayOperation.addObserver(LoggingObserver())
let otherOperation = BlockOperation {
    print("other block completion")
}
otherOperation.addDependency(delayOperation)
otherOperation.addObserver(LoggingObserver())
let queue = OperationQueue()
queue.addOperations([delayOperation, otherOperation], waitUntilFinished: false)
queue.cancelAllOperations()
```
leads to both the `DelayOperation` and `BlockOperation` executing successfully. Looking at the code it seems like neither of these classes override `cancel` and so execute completely. Is this intentional?

**Comment by danthorpe** [comment] 2015-12-14 18:05
Hi @jshier - nope, not intentional at all. Consider this a bug, will fix it.

**Comment by danthorpe** [comment] 2015-12-14 18:59
Okay, looking more closely at `DelayOperation` - we do check the `cancelled` state inside the `dispatch_after` closure. Which is where the operation is finished. If it is cancelled, then `finish` has already been called. In which case, the completion block will have been executed. 

Note that from the `NSOperation` [docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSOperation_class/#//apple_ref/occ/instp/NSOperation/completionBlock) on `completionBlock`:

> A finished operation may finish either because it was cancelled or because it successfully completed its task. You should take that fact into account when writing your block code. Similarly, you should not make any assumptions about the successful completion of dependent operations, which may themselves have been cancelled.

So, despite the delay operation being cancelled, the above code should still print out `delay completion block` - again, I do see this as yet another unexpected (albeit documented) behavior of `NSOperation`. So - not a bug in `DelayOperation`, although in theory there is scope to improve the way the delay operation spends its time to support more frequent checking of `cancelled`.

In terms of `BlockOperation` - I think there is a bug here, because the `execute` implementation doesn't check the state of `cancelled`.

**Comment by jshier** [comment] 2015-12-14 21:35
I think some of this comes down to my (continued) misunderstanding of how the cancellation of operations works. I think, fundamentally, I was assuming that the cancellation of operations would invalidate any dependency chain established and dependent operations wouldn't even execute. (Which I think I've done before when reporting bugs here.) Now that I think about it, that's the reason for conditions, isn't it? 

For `DelayOperation`, and I correct in understanding that, while the cancellation sets the operation to the finished state immediately, the `dispatch_after` is still running and will always execute it's block? Seems like a `dispatch_source` might be better here, so it can be cancelled and the block never run in the first place.

For `BlockOperation`, I would expect not to have the block executed if the operation is cancelled, which I think is the logical behavior.

**Comment by danthorpe** [comment] 2015-12-14 21:49
Hi @jshier well... I can't count how many times I've read the NSOperation documentation and found that I still don't fully get how it works, or that my understanding doesn't match up with what I've observed in practice 😖 - so I fully understand.

Indeed, I'm just trying to write some test cases to validate my understanding on this, and I've discovered that taking your example code above, if I cancel only the `DelayOperation`, the test fails because the `BlockOperation` is not executed - which as I understood the docs - is not correct.... 🤔

Regarding `DelayOperation` - you are correct, that yes, the `dispatch_after` will continue and so yes, I think a `dispatch_source` would improve it for sure. I'm not going to do that now though.

For `BlockOperation` I think this is more straightforward - if it is cancelled before it executes, then the block should not be run. So, I will fix this bug shortly.

**Comment by danthorpe** [comment] 2015-12-14 21:59
For example, this is from the `cancel()` [docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSOperation_class/#//apple_ref/occ/instm/NSOperation/cancel):

> In OS X v10.6 and later, if an operation is in a queue but waiting on unfinished dependent operations, those operations are subsequently ignored. Because it is already cancelled, this behavior allows the operation queue to call the operation’s start method sooner and clear the object out of the queue. 

I can't tell if that means, if you cancel the operation that is waiting, or if you cancel the dependent operations... I think it's really vague - the language uses "it" a lot when discussing different operation instances.

**Comment by danthorpe** [comment] 2015-12-14 23:30
Hi @jshier and... regarding `BlockOperation` - I have added a check on `cancelled` anyway, but also I don't think it should be an issue, because `NSOperation` / `Operation` ensures that when cancelled the operation goes from start direct to finish, it doesn't call `main`, which in turn means that `execute` isn't called, so the block isn't executed. I've added a test to verify this too.

**Comment by danthorpe** [comment] 2015-12-14 23:44
So.... if you have the following code:

```swift
LogManager.severity = .Verbose
let delayOperation = DelayOperation(interval: 5)
delayOperation.completionBlock = { print("delay completion block") }
let otherOperation = BlockOperation {
    print("other block completion")
}
otherOperation.addDependency(delayOperation)
let queue = OperationQueue()
queue.addOperations([delayOperation, otherOperation], waitUntilFinished: false)
queue.cancelAllOperations()
```

You'll get this output...

```
Delay for 5.0 seconds: Initialized -> Pending
Delay for 5.0 seconds: Pending -> Ready
Block Operation: Initialized -> Pending
Delay for 5.0 seconds: Did cancel.
Block Operation: Did cancel.
Delay for 5.0 seconds: Ready -> Executing
Block Operation: Pending -> Finishing
Delay for 5.0 seconds: Will Execute
Block Operation: Did finish with no errors.
Block Operation: Finishing -> Finished
```

So what is happening here? And is it correct?

So both operations cancel and then enter `.Executing` state. I think this is because we cancel all the operations after we add them to the queue. As soon as the operations are added to the queue the `DelayOperation` should begin executing at approximately the same time as it is cancelled. The `BlockOperation` is then cancelled (by the queue) and so it immediately goes from `.Pending` to `.Finished`. It didn't immediately start because it was depending on the `DelayOperation`. So - that all makes sense and is correct from what I understand and observe from `NSOperation`.

There is one thing which is a little odd though.... the `completionBlock` of the `DelayOperation` does not get called, and I think it should be called when the operation finishes (regardless of a cancellation).

So.. I think there is still an issue with cancellation in `NSOperation`, we do override it, but only to print out some log info, and then we call super. Also PSOperations had this commit: https://github.com/pluralsight/PSOperations/commit/e07f02b21aa4ecce748688b3400114c41680afdf which suggests a bug involving `NSOperation`, `cancel()` and `isFinished`.

**Comment by danthorpe** [comment] 2015-12-15 11:18
@jshier what do you make of this?

**Comment by danthorpe** [comment] 2015-12-15 12:30
So, I've now added cancelled state to `Operation`. All this really does is provide a boolean which is then shadowed by `cancelled`. With this in place, running the above code produces the following output:

```
Delay for 5.0 seconds: Initialized -> Pending
delay completion block
Delay for 5.0 seconds: Pending -> Ready
Block Operation: Initialized -> Pending
Delay for 5.0 seconds: Did cancel.
Delay for 5.0 seconds: Ready -> Executing
Delay for 5.0 seconds: Executing -> Finishing
Delay for 5.0 seconds: Will Execute
Delay for 5.0 seconds: Did finish with no errors.
Delay for 5.0 seconds: Finishing -> Finished
Block Operation: Did cancel.
Block Operation: Pending -> Ready
Block Operation: Ready -> Finishing
Block Operation: Did finish with no errors.
Block Operation: Finishing -> Finished
``` 

The crucial difference here is that the `completionBlock` for `DelayOperation` is executed correctly - see the 2nd line. But still the `BlockOperation` is not executed.

**Comment by danthorpe** [comment] 2015-12-15 14:11
@jshier okay, I've merged #134 which hopefully will improve how this kind of scenario has been working for you. The changes in this PR had the following:

1. Fixes a bug (I think in `NSOperation`) where completion block would not be called if an operation is cancelled.
2. Adds more logging around cancellation
3. Refactors `DelayOperation` to use `dispatch_source_t`
4. Provides more safety with `BlockOperation` to check cancelled state before running the block.
5. Added a bunch of tests to validate / confirm expected behavior regarding cancellation. I would say that there are 4 situations here, cancelling a operation before adding to a queue, after adding to a queue, cancelling a dependency after added to the queue but while waiting for the dependency, and cancelling all operations on the queue.

I'm not sure if I've necessarily addressed all the things you raised here - but I think I have made it so that `Operation` and subclasses do behave as expected according to the `NSOperation` documentation.

**Comment by jshier** [comment] 2015-12-15 16:58
Sorry, I wanted to do more analysis on my end before responding but you've jumped ahead now. My contrived test case works as I would expect now. And `DelayOperation` is much nicer. I'll give my app a try on the development branch, and audit my custom operations' cancellation behavior. Thanks.

**Comment by danthorpe** [comment] 2015-12-15 17:02
Hey @jshier - yeah, sorry for jumping the gun, I wanted to crack on. I would hold off on auditing/changing any of your custom operations' cancellation behavior just yet. See #132 which adds a cancellation callback to the `OperationObserver` - see https://github.com/danthorpe/Operations/commit/8960a93ceec1a3000f7fe3ab76bfc5478b2f6184 for how it should be used.

The reasoning behind this is that the block is only called once (the first time that the operation is cancelled). Should hopefully merge #132 today.

**Comment by jshier** [comment] 2015-12-15 19:12
I see in #132 you're changing several operation classes to use the cancellation observer for their cancellation logic. What's the advantage of that versus the standard `override cancel()`? A workaround for `cancel()` not being called?

**Comment by danthorpe** [comment] 2015-12-15 19:47
Hey @jshier - well the reasoning is that, in most of these cases the code which is in the over-ridden `cancel()` only wants to be called once. For example, `stopUpdatingLocation()` or `dispatch_source_cancel()`. So, the combination of `OperationObserver` & `Operation` can remove a lot of the boilerplate/state management which *should be* in all of those sub-classes.

What do you think? I guess I'm a little concerned that they look like significant departures - but we have unit tests for this right?

**Comment by jshier** [comment] 2015-12-15 21:34
Called only once? Could `cancel()` be called more than once?

My main concern is consistency and best practice. While I customize `Operation` subclasses by overriding things like `execute()`, to implement custom cancellation behavior I have to use an observer? Which is the right or best way? Also, developers may be confused about which to implement in the first place, since everything else is done through overrides.

**Comment by danthorpe** [comment] 2015-12-15 22:26
Well, I'm following recent changes in another advanced operations style framework: https://github.com/pluralsight/PSOperations/pull/31 (from @davedelong).

As I've discovered with recent debugging & general checking, I think because of the key-value coding/observing nature of `NSOperation`, queues, operations and their dependencies I don't expect that it is guaranteed the `cancel` method is only ever called once. In general side effects of state change should be idempotent - however, often with cancellation this isn't possible without additional flags.

So... if you need to make sure that you definitely only execute the side effects of operation cancellation once - it's easiest to use a `BlockObserver`. But, overriding `cancel` and calling `super.cancel` is probably okay for most cases.

Before v2.5 of this framework is released I'm going to have a bit of an overhaul of the README and might even add some Wiki pages for best-practices / how-to do common things.

**Comment by danthorpe** [comment] 2015-12-17 18:00
Hi @jshier, are there any more thoughts on this? Can I close this?

**Comment by jshier** [comment] 2015-12-17 18:02
I've tested the new `DelayOperation` in my code and it works well. No further comments. I'm looking forward to 2.5.

**Comment by danthorpe** [comment] 2015-12-17 18:02
:+1:

**Closed by danthorpe** 2015-12-17 18:02 UTC
Labels: bug, waiting for response
