### ISSUE TITLE
Crash in operation dealloc

### ISSUE THREAD

**Issue by jshier** [danthorpe/Operations#50] opened 2015-08-14 20:15 UTC
If you remember my previous question, I have a `NetworkOperation`, which wraps an Alamofire `Request`. I'm attempting to update my operations to not use the completion handlers but store state in the class, as suggested. However, after making that change I'm hitting a crash at runtime when the operation is deallocated. Here's my operation:
```swift
class NetworkOperation<T: Decodable where T == T.DecodedType> : Operation {
    let request: Request
    var responseObject: T? = nil
    
    init(request: Request) {
        self.request = request
        
        super.init()
        
        request.responseObject { (responseObject: T?, error: APIError?) in
            self.responseObject = responseObject
            self.finish(error)
        }
        
        addObserver(NetworkObserver())
    }
    
    override func execute() {
        request.resume()
    }
    
    override func cancel() {
        request.cancel()
        super.cancel()
    }
}
```
And here's the crash:
```
thread #1: tid = 0x223dc1, 0x000000010c6dacea libswiftCore.dylib`_swift_release_(swift::HeapObject*) + 10, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x000000010c6dacea libswiftCore.dylib`_swift_release_(swift::HeapObject*) + 10
    frame #1: 0x000000010672deda App`@objc App.NetworkOperation.__ivar_destroyer + 74 at NetworkOperation.swift:0
    frame #2: 0x000000010c02f7bb libobjc.A.dylib`object_cxxDestructFromClass(objc_object*, objc_class*) + 127
    frame #3: 0x000000010c03a390 libobjc.A.dylib`objc_destructInstance + 93
    frame #4: 0x000000010c03a3c3 libobjc.A.dylib`object_dispose + 22
    frame #5: 0x0000000108998a6f Foundation`-[NSOperation dealloc] + 89
    frame #6: 0x0000000108a01b49 Foundation`NSKVODeallocate + 94
    frame #7: 0x000000010c044afe libobjc.A.dylib`objc_object::sidetable_release(bool) + 232
    frame #8: 0x000000010c0450b8 libobjc.A.dylib`(anonymous namespace)::AutoreleasePoolPage::pop(void*) + 488
    frame #9: 0x000000010b3c5446 CoreFoundation`_CFAutoreleasePoolPop + 22
    frame #10: 0x000000010b3f93c1 CoreFoundation`__CFRunLoopRun + 2081
    frame #11: 0x000000010b3f8918 CoreFoundation`CFRunLoopRunSpecific + 488
    frame #12: 0x000000010dc7fad2 GraphicsServices`GSEventRunModal + 161
    frame #13: 0x000000010997699e UIKit`UIApplicationMain + 171
  * frame #14: 0x0000000106633e5d App`main + 109 at AppDelegate.swift:12
    frame #15: 0x000000010cbed92d libdyld.dylib`start + 1
    frame #16: 0x000000010cbed92d libdyld.dylib`start + 1
```
I suspect this is just a compiler bug but this is a rather big blocker. Any suggestions or have you seen anything like this before?

**Comment by danthorpe** [comment] 2015-08-15 01:38
Hey @jshier haven't seen anything like this....

Can you change your request handler closure to not capture self, use [weak self] or [unowned self]. While this retain cycle might not be the cause, it's probably going to confuse this debugging. 

If that doesn't fix it - can you share a mini project that re-produces the crash? Can you share/attach the request class?

**Comment by danthorpe** [comment] 2015-08-17 23:30
@jshier any news on this ticket?

**Comment by jshier** [comment] 2015-08-19 00:16
I'll see if I can create a minimized project that reproduces this, but it'll be a little while before I have time.

**Comment by danthorpe** [comment] 2015-08-19 01:14
But what about the retain cycle - I'm pretty sure this is causing the crash. The operation owns the request, the request owns a closure, which strongly captures self. At the very least you've got a memory leak as the operation can never be released.

If you just change the closure to capture self weakly using [weak self] then it will not crash.

**Comment by danthorpe** [comment] 2015-08-19 09:56
I'm going to close this issue, as it's not re-producible without deliberately introducing a retain cycle.

**Closed by danthorpe** 2015-08-19 09:56 UTC
Labels: waiting for response
