### ISSUE TITLE
CloudKitOperation execute method...

### ISSUE THREAD

**Issue by StephenDaedalus** [danthorpe/Operations#158] opened 2016-01-04 19:27 UTC
I'm wondering how to properly queue a concrete instance of a CloudKitOperation. 

When I add it to an OperationQueue, the execute() method gets invoked but an illegal state transition assertion is thrown when my CloudKitOperation goes from .Initializing to .Finishing.  

The actual NSOperation is queued to the CKDatabase and completes successfully but there's something amiss in the coordination between the wrapped NSOperation and the CloudKitOperation. I'm sure it's just the way that I've created the instance and queued it.

Should there be any changes to the execute() method?

    public override func execute() {
        operation.addCompletionBlock {
            self.finish()
        }
        operation.begin()
    }

**Comment by danthorpe** [comment] 2016-01-04 20:26
Hi @StephenDaedalus thanks for the feedback, and I think I'll refactor `CloudKitOperation` to work better based on this issue.

But, as discussed [in the support forums](https://operations.readme.io/v2.5.0/discuss/568ac574d4e2360d0098008e) this issue is caused by calling `execute` directly from within an enclosing `Operation`.

**Comment by danthorpe** [comment] 2016-01-06 00:17
Going to close this issue now as it's been resolved. 

There is work underway which will refactor the `CloudKitOperation` in #160, which will be merged into master in version 2.6.

**Closed by danthorpe** 2016-01-06 00:17 UTC
Labels: question
